import Dependencies._

ThisBuild / scalaVersion     := "3.4.2"
ThisBuild / version          := "0.1.0-SNAPSHOT"
ThisBuild / organization     := "org.exercism"
ThisBuild / organizationName := "exercism"

lazy val root = (project in file("."))
  .settings(
    name := "TestRunner",
    // `TestRun` has a main method of its own, so the class to start on `java -jar` has to be spelled out.
    assembly / mainClass := Some("run"),
    // not in the Test scope so that it gets added to the fat jar generated by sbt assembly
    libraryDependencies += scalaTest,
    libraryDependencies += scalaCheck,
    libraryDependencies += json,
    // for the LensPerson exercise
    libraryDependencies ++= monocle,
    // for the SgfParsing, Alphametics, Forth, MatchingBrackets and Wordy exercises
    libraryDependencies += parserCombinators
  )
